// Embeds src/lib/sandbox/worldsim.py into a TypeScript module so the API route can upload it
// to the model's Python sandbox without relying on filesystem access at runtime.
import fs from "node:fs";
import path from "node:path";
const root = path.resolve(new URL(".", import.meta.url).pathname, "..");
const src = fs.readFileSync(path.join(root, "src/lib/sandbox/worldsim.py"), "utf8");
const out = `// GENERATED by scripts/embed-sandbox.mjs from src/lib/sandbox/worldsim.py. Do not edit.\nexport const WORLDSIM_PY = ${JSON.stringify(src)};\n`;
fs.writeFileSync(path.join(root, "src/lib/sandbox/worldsim_py.ts"), out);
console.log("embedded worldsim.py (" + src.length + " chars)");
